services:
  #-----------------------------------
  #---------------KAFKA==-------------
  #-----------------------------------
  kafka:
    image: apache/kafka:4.2.1
    container_name: shopcore-kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - shopcore-network
  #-----------------------------------
  #-------------DATABASES-------------
  #-----------------------------------
  product-db:
    image: postgres:16-alpine
    container_name: shopcore-product-db
    environment:
      POSTGRES_DB: shop_product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - product-db-data:/var/lib/postgresql/data
    networks:
      - shopcore-network
  auth-db:
    image: postgres:16-alpine
    container_name: shopcore-auth-db
    environment:
      POSTGRES_DB: shop_auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - shopcore-network
  order-db:
    image: postgres:16-alpine
    container_name: shopcore-order-db
    environment:
      POSTGRES_DB: shop_order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data
    networks:
      - shopcore-network
  payment-db:
    image: postgres:16-alpine
    container_name: shopcore-payment-db
    environment:
      POSTGRES_DB: shop_payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - payment-db-data:/var/lib/postgresql/data
    networks:
      - shopcore-network

  #-----------------------------------
  #-------------SERVICES--------------
  #-----------------------------------
  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    container_name: shopcore-product-service
    depends_on:
      - product-db
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-db:5432/shop_product_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: change-this-secret-change-this-secret-123456
    ports:
      - "8081:8081"
    networks:
      - shopcore-network

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: shopcore-auth-service
    depends_on:
      - auth-db
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/shop_auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: change-this-secret-change-this-secret-123456
      JWT_EXPIRATION_MINUTES: 60
    ports:
      - "8082:8082"
    networks:
      - shopcore-network

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: shopcore-order-service
    depends_on:
      - order-db
      - product-service
      - kafka
    environment:
      SERVER_PORT: 8083
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/shop_order_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: change-this-secret-change-this-secret-123456
      PRODUCT_SERVICE_URL: http://product-service:8081
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8083:8083"
    networks:
      - shopcore-network

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    container_name: shopcore-payment-service
    depends_on:
      - payment-db
      - order-service
      - kafka
    environment:
      SERVER_PORT: 8084
      SPRING_DATASOURCE_URL: jdbc:postgresql://payment-db:5432/shop_payment_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: change-this-secret-change-this-secret-123456
      ORDER_SERVICE_URL: http://order-service:8083
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8084:8084"
    networks:
      - shopcore-network


  #-----------------------------------
  #--------------GATEWAY--------------
  #-----------------------------------
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: shopcore-api-gateway
    depends_on:
      - auth-service
      - product-service
      - order-service
      - payment-service
    environment:
      SERVER_PORT: 8080
      JWT_SECRET: change-this-secret-change-this-secret-123456
    ports:
      - "8080:8080"
    networks:
      - shopcore-network

  #-----------------------------------
  #--------VOLUMES & NETWORKS---------
  #-----------------------------------

volumes:
  product-db-data:
  auth-db-data:
  order-db-data:
  payment-db-data:

networks:
  shopcore-network:
    driver: bridge