services:
  product-db:
    image: postgres:16-alpine
    container_name: shopcore-product-db
    environment:
      POSTGRES_DB: shop_product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - product-db-data:/var/lib/postgresql/data
    networks:
      - shopcore-network
  auth-db:
    image: postgres:16-alpine
    container_name: shopcore-auth-db
    environment:
      POSTGRES_DB: shop_auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - shopcore-network

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    container_name: shopcore-product-service
    depends_on:
      - product-db
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-db:5432/shop_product_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: change-this-secret-change-this-secret-123456
    ports:
      - "8081:8081"
    networks:
      - shopcore-network

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: shopcore-auth-service
    depends_on:
      - auth-db
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/shop_auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: change-this-secret-change-this-secret-123456
      JWT_EXPIRATION_MINUTES: 60
    ports:
      - "8082:8082"
    networks:
      - shopcore-network

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: shopcore-api-gateway
    depends_on:
      - auth-service
      - product-service
    environment:
      SERVER_PORT: 8080
      JWT_SECRET: change-this-secret-change-this-secret-123456
    ports:
      - "8080:8080"
    networks:
      - shopcore-network

volumes:
  product-db-data:
  auth-db-data:

networks:
  shopcore-network:
    driver: bridge