spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://auth-service:8082
              predicates:
                - Path=/api/auth/**,/api/users/**,/api/admin/**

            - id: product-service
              uri: http://product-service:8081
              predicates:
                - Path=/api/products/**

            - id: order-service
              uri: http://order-service:8083
              predicates:
                - Path=/api/orders/**

server:
  port: ${SERVER_PORT:8080}

app:
  security:
    jwt:
      secret: ${JWT_SECRET:change-this-secret-change-this-secret-123456}